/**
 * Prisma seed script — run with: pnpm exec prisma db seed
 * Upserts 25 diverse demo products and 2 default users (idempotent).
 */
import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const DEMO_PRODUCTS = [
    // ── Physical / US ─────────────────────────────────────────────────────────
    {
        title: "Wireless Noise-Cancelling Headphones",
        slug: "wireless-noise-cancelling-headphones",
        description: "Premium over-ear headphones with 40-hour battery life and active noise cancellation. Perfect for travel and studio use.",
        price: 299.99,
        stock: 45,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Black", "Silver", "Midnight Blue"],
        images: ["https://picsum.photos/seed/headphones/800/600"],
    },
    {
        title: "Mechanical Keyboard Pro",
        slug: "mechanical-keyboard-pro",
        description: "TKL mechanical keyboard with Cherry MX switches and per-key RGB lighting. Aluminium top plate.",
        price: 159.99,
        stock: 120,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Black", "White"],
        images: ["https://picsum.photos/seed/keyboard/800/600"],
    },
    {
        title: "27-inch 4K Monitor",
        slug: "27-inch-4k-monitor",
        description: "IPS panel, 144 Hz, 1 ms, HDR600, USB-C 96 W — made for creators and gamers who demand the best.",
        price: 549.99,
        stock: 30,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Black"],
        images: ["https://picsum.photos/seed/monitor/800/600"],
    },
    {
        title: "Ergonomic Standing Desk",
        slug: "ergonomic-standing-desk",
        description: "Electric height-adjustable desk with memory presets and anti-collision technology. Dual motor system.",
        price: 649.99,
        stock: 15,
        status: "active",
        type: "physical",
        region: "US",
        sizes: ["120cm", "140cm", "160cm"],
        colors: ["White", "Walnut", "Black"],
        images: ["https://picsum.photos/seed/desk/800/600"],
    },
    {
        title: "Portable SSD 2 TB",
        slug: "portable-ssd-2tb",
        description: "NVMe portable SSD with 2,000 MB/s read and shockproof aluminium shell. USB-C 3.2 Gen 2.",
        price: 179.99,
        stock: 80,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Silver", "Black"],
        images: ["https://picsum.photos/seed/ssd/800/600"],
    },
    // ── Physical / EU ─────────────────────────────────────────────────────────
    {
        title: "4K Webcam Ultra",
        slug: "4k-webcam-ultra",
        description: "4K 60 fps webcam with built-in ring light and AI background removal. Plug-and-play USB-C.",
        price: 119.99,
        stock: 60,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["Black", "White"],
        images: ["https://picsum.photos/seed/webcam/800/600"],
    },
    {
        title: "USB-C 240W Hub",
        slug: "usb-c-240w-hub",
        description: "12-in-1 hub: dual 4K HDMI, 10 Gbps USB-A/C, SD, Ethernet, 240W PD. Works with all laptops.",
        price: 89.99,
        stock: 200,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["Silver", "Space Grey"],
        images: ["https://picsum.photos/seed/hub/800/600"],
    },
    {
        title: "Smart Desk Lamp",
        slug: "smart-desk-lamp",
        description: "Adaptive LED lamp with wireless charging base and touch dimmer. Works with Alexa & Google Home.",
        price: 49.99,
        stock: 150,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["White", "Black"],
        images: ["https://picsum.photos/seed/lamp/800/600"],
    },
    {
        title: "Noise-Isolating Earbuds",
        slug: "noise-isolating-earbuds",
        description: "True wireless earbuds with custom-tuned drivers and 32-hour total playback including case.",
        price: 129.99,
        stock: 90,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: ["S", "M", "L"],
        colors: ["Black", "White", "Rose Gold"],
        images: ["https://picsum.photos/seed/earbuds/800/600"],
    },
    {
        title: "Compact Air Purifier",
        slug: "compact-air-purifier",
        description: "HEPA H13 purifier for spaces up to 30 m². Ultra-quiet 25 dB sleep mode. PM2.5 sensor.",
        price: 99.99,
        stock: 40,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["White", "Black"],
        images: ["https://picsum.photos/seed/purifier/800/600"],
    },
    {
        title: "Laptop Stand Pro",
        slug: "laptop-stand-pro",
        description: "Aluminium multi-angle laptop stand with cable management channel and phone slot. Folds flat.",
        price: 39.99,
        stock: 300,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["Silver", "Space Grey"],
        images: ["https://picsum.photos/seed/stand/800/600"],
    },
    // ── Physical / Asia ───────────────────────────────────────────────────────
    {
        title: "Wireless Charging Pad",
        slug: "wireless-charging-pad",
        description: "Qi2 15 W magnetic charging pad compatible with all Qi-enabled devices. Ultra-thin 5 mm profile.",
        price: 29.99,
        stock: 500,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: [] as string[],
        colors: ["White", "Black"],
        images: ["https://picsum.photos/seed/charger/800/600"],
    },
    {
        title: "Smart Plug 4-Pack",
        slug: "smart-plug-4-pack",
        description: "Wi-Fi smart plugs with energy monitoring, scheduling, and voice assistant support. No hub required.",
        price: 34.99,
        stock: 220,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: [] as string[],
        colors: ["White"],
        images: ["https://picsum.photos/seed/plug/800/600"],
    },
    {
        title: "Magnetic Cable Organiser",
        slug: "magnetic-cable-organiser",
        description: "Silicone magnetic cable clips with strong adhesive base — set of 10. Keeps desk tidy.",
        price: 12.99,
        stock: 1000,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: [] as string[],
        colors: ["Black", "White", "Red"],
        images: ["https://picsum.photos/seed/cables/800/600"],
    },
    {
        title: "Desk Mat XL",
        slug: "desk-mat-xl",
        description: "900 × 400 mm stitched desk mat with non-slip rubber base — 12 colour options available.",
        price: 24.99,
        stock: 400,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: ["M", "XL", "XXL"],
        colors: ["Black", "Navy", "Green", "Pink"],
        images: ["https://picsum.photos/seed/mat/800/600"],
    },
    {
        title: "RGB Gaming Mousepad",
        slug: "rgb-gaming-mousepad",
        description: "Extended RGB mousepad with 14 lighting modes, braided USB cable, and micro-textured surface.",
        price: 44.99,
        stock: 180,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: ["M", "XL"],
        colors: ["Black"],
        images: ["https://picsum.photos/seed/mousepad/800/600"],
    },
    // ── Out-of-stock / limited ─────────────────────────────────────────────────
    {
        title: "Stream Deck XL",
        slug: "stream-deck-xl",
        description: "32-key customisable LCD stream controller for streamers, editors and power users.",
        price: 249.99,
        stock: 0,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Black"],
        images: ["https://picsum.photos/seed/streamdeck/800/600"],
    },
    {
        title: "Thunderbolt 4 Dock",
        slug: "thunderbolt-4-dock",
        description: "11-port Thunderbolt 4 dock with dual 4K display support, 96 W laptop charging, 2.5G Ethernet.",
        price: 319.99,
        stock: 8,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Silver"],
        images: ["https://picsum.photos/seed/dock/800/600"],
    },
    // ── Digital / Software & Courses ──────────────────────────────────────────
    {
        title: "UI Design Masterclass",
        slug: "ui-design-masterclass",
        description: "40+ hours of premium UI/UX design training: Figma, design systems, prototyping and usability testing.",
        price: 79.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "US",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/uidesign/800/600"],
    },
    {
        title: "Full-Stack JavaScript Bootcamp",
        slug: "full-stack-js-bootcamp",
        description: "Complete Node.js + React curriculum with 20 real-world projects, certificate included.",
        price: 129.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "US",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/bootcamp/800/600"],
    },
    {
        title: "Notion Productivity Bundle",
        slug: "notion-productivity-bundle",
        description: "50 premium Notion templates: project management, habit tracker, CRM and life OS.",
        price: 29.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "EU",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/notion/800/600"],
    },
    {
        title: "Figma Component Library Pro",
        slug: "figma-component-library-pro",
        description: "1,200+ production-ready components with auto-layout, dark/light mode, and full documentation.",
        price: 59.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "EU",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/figma/800/600"],
    },
    {
        title: "E-Commerce Photography Presets",
        slug: "ecommerce-photography-presets",
        description: "Pack of 85 Lightroom presets optimised for product photography — clean, bright, professional.",
        price: 19.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "Asia",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/presets/800/600"],
    },
    {
        title: "Stock Icon Pack — 4,000 Icons",
        slug: "stock-icon-pack-4000",
        description: "4,000 pixel-perfect SVG icons in 6 styles: outline, filled, duotone, color, solid, and rounded.",
        price: 39.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "Asia",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/icons/800/600"],
    },
    {
        title: "NestJS API Starter Kit",
        slug: "nestjs-api-starter-kit",
        description: "Production-ready NestJS boilerplate: JWT auth, Prisma ORM, Docker, Swagger, CI/CD pipelines.",
        price: 49.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "US",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/nestjs/800/600"],
    },
    // ── Additional Products ──────────────────────────────────────────────────
    {
        title: "4K Ultra Short Throw Projector",
        slug: "4k-ultra-short-throw-projector",
        description: "Experience cinema at home with 2500 ANSI lumens, HDR10, and built-in Harman Kardon speakers.",
        price: 1899.99,
        stock: 5,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["White", "Black"],
        images: ["https://picsum.photos/seed/projector/800/600"],
    },
    {
        title: "Professional XLR Studio Mic",
        slug: "professional-xlr-studio-mic",
        description: "Large-diaphragm cardioid condenser microphone. Crystal clear audio for vocals and instruments.",
        price: 249.00,
        stock: 25,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["Black", "Silver"],
        images: ["https://picsum.photos/seed/mic/800/600"],
    },
    {
        title: "Ergonomic Office Chair Elite",
        slug: "ergonomic-office-chair-elite",
        description: "Breathable mesh, adjustable lumbar support, and 4D armrests. Designed for 12+ hours of comfort.",
        price: 499.00,
        stock: 12,
        status: "active",
        type: "physical",
        region: "US",
        sizes: ["Standard", "Large"],
        colors: ["Space Grey", "Midnight Black"],
        images: ["https://picsum.photos/seed/chair/800/600"],
    },
    {
        title: "Python for Data Science Course",
        slug: "python-for-data-science-course",
        description: "Master NumPy, Pandas, Matplotlib and Scikit-Learn. Includes 15 real-world datasets and projects.",
        price: 89.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "Asia",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/python/800/600"],
    },
    {
        title: "Minimalist Vector Icon Set",
        slug: "minimalist-vector-icon-set",
        description: "2,500+ handcrafted icons in AI, SVG, and PNG formats. Perfect for modern web and mobile apps.",
        price: 24.50,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "EU",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/icons2/800/600"],
    },
    {
        title: "Gaming Controller Ultra",
        slug: "gaming-controller-ultra",
        description: "Wireless controller with haptic feedback, adaptive triggers, and 20-hour rechargeable battery.",
        price: 69.99,
        stock: 150,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: [] as string[],
        colors: ["White", "Black", "Camouflage"],
        images: ["https://picsum.photos/seed/controller/800/600"],
    },
    {
        title: "Foldable 4K Camera Drone",
        slug: "foldable-4k-camera-drone",
        description: "GPS-enabled drone with 3-axis gimbal, 30-min flight time, and 10km video transmission range.",
        price: 749.00,
        stock: 10,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Grey"],
        images: ["https://picsum.photos/seed/drone/800/600"],
    },
    {
        title: "E-Ink Writing Tablet",
        slug: "e-ink-writing-tablet",
        description: "The paper-like feel for note-taking and reading. No glares, no distractions, weeks of battery.",
        price: 399.99,
        stock: 40,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: ["10-inch"],
        colors: ["Grey"],
        images: ["https://picsum.photos/seed/tablet/800/600"],
    },
    {
        title: "Smart Home Security Kit",
        slug: "smart-home-security-kit",
        description: "Includes 4 cameras, 2 motion sensors, and a central hub. Full mobile control and night vision.",
        price: 329.00,
        stock: 35,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["White"],
        images: ["https://picsum.photos/seed/security/800/600"],
    },
    {
        title: "Organic Yoga Mat Premium",
        slug: "organic-yoga-mat-premium",
        description: "Extra thick, non-slip, and made from sustainable natural rubber. Anti-microbial surface.",
        price: 75.00,
        stock: 85,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: ["Standard", "Extra Long"],
        colors: ["Forest Green", "Deep Purple", "Sand"],
        images: ["https://picsum.photos/seed/yoga/800/600"],
    },
    {
        title: "Stainless Steel Cookware Set",
        slug: "stainless-steel-cookware-set",
        description: "12-piece professional grade set. Tri-ply construction for even heat distribution.",
        price: 299.00,
        stock: 20,
        status: "active",
        type: "physical",
        region: "EU",
        sizes: [] as string[],
        colors: ["Chrome"],
        images: ["https://picsum.photos/seed/cookware/800/600"],
    },
    {
        title: "Electric Milk Frother",
        slug: "electric-milk-frother",
        description: "Get café-quality foam in seconds. Hot and cold frothing modes. Easy to clean.",
        price: 39.99,
        stock: 120,
        status: "active",
        type: "physical",
        region: "Asia",
        sizes: [] as string[],
        colors: ["Black", "White", "Red"],
        images: ["https://picsum.photos/seed/frother/800/600"],
    },
    {
        title: "Travel Backpack 45L",
        slug: "travel-backpack-45l",
        description: "Carry-on sized, water-resistant, with dedicated tech organization and hidden security pockets.",
        price: 145.00,
        stock: 55,
        status: "active",
        type: "physical",
        region: "US",
        sizes: [] as string[],
        colors: ["Black", "Navy", "Olive"],
        images: ["https://picsum.photos/seed/backpack/800/600"],
    },
    {
        title: "Web Accessibility Course",
        slug: "web-accessibility-course",
        description: "Learn to build inclusive websites. Covers WCAG 2.2, ARIA, and screen reader testing.",
        price: 59.99,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "EU",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/a11y/800/600"],
    },
    {
        title: "Vintage Cinema Poster Set",
        slug: "vintage-cinema-poster-set",
        description: "High-resolution digital downloads of 50 classic film posters. Print-ready formats.",
        price: 15.00,
        stock: 9999,
        status: "active",
        type: "digital",
        region: "US",
        sizes: [] as string[],
        colors: [] as string[],
        images: ["https://picsum.photos/seed/posters/800/600"],
    },
];

async function main() {
    console.log("Seeding database …");

    // ── Seed users ────────────────────────────────────────────────────────────
    const adminHash = await bcrypt.hash("Admin1234!", 12);
    await prisma.user.upsert({
        where: { email: "admin@example.com" },
        update: {},
        create: {
            name: "Admin User",
            email: "admin@example.com",
            password: adminHash,
            role: "admin",
        },
    });

    const userHash = await bcrypt.hash("User1234!", 12);
    await prisma.user.upsert({
        where: { email: "user@example.com" },
        update: {},
        create: {
            name: "Test User",
            email: "user@example.com",
            password: userHash,
            role: "user",
        },
    });

    console.log("✔ Users seeded");

    // ── Seed products ─────────────────────────────────────────────────────────
    for (const product of DEMO_PRODUCTS) {
        await prisma.product.upsert({
            where: { slug: product.slug },
            update: {
                type: product.type,
                region: product.region,
                sizes: product.sizes,
                colors: product.colors,
            },
            create: { ...product, currency: "USD" },
        });
    }

    console.log(`✔ ${DEMO_PRODUCTS.length} products seeded`);
    console.log("✅ Done");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(() => prisma.$disconnect());
